---
title: "Vowel duration and tongue root advancement in Italian and Polish"
author: "Stefano Coretta"
date: "18/09/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_minimal())
library(rticulate) # https://github.com/stefanocoretta/rticulate
library(stringr)
library(scales)
library(tidymv) # https://github.com/stefanocoretta/tidymv
library(itsadug)
library(lmerTest)
library(effects)
options(contrasts = rep ("contr.treatment", 2))
```

# Import data

`tongues` contains splines coordinates at maximum displacement, `tongues_clos` has splines coordinates at acoustic closure, and `vowels` has durational data.

```{r data}
languages <- read_csv("data/languages.csv")
words <- read_csv("data/nonce.csv")

columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs"
)

aaa_files <- list.files(
    path = "./data/tongue",
    pattern = "*-tongue-cart.tsv",
    full.names = TRUE
)

tongues <- read_aaa(
    aaa_files,
    columns, 
    na.rm = TRUE
) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor) %>%
    group_by(speaker) %>%
    mutate(
        X.re = rescale(X),
        Y.re = rescale(Y)
    ) %>%
    ungroup() %>%
    mutate(
        vowel.ord = ordered(vowel, levels = c("a", "o", "u")),
        c2place.ord = ordered(c2place, levels = c("coronal", "velar")),
        c2phonation.ord = ordered(c2phonation, levels = c("voiceless", "voiced"))
    ) %>%
    filter(label %in% c("max_TT", "max_TD"), vowel != "u") %>%
    arrange(rec.date, fan.line) %>%
    create_event_start("rec.date")

aaa_files_clos <- list.files(
    path = "./data/tongue",
    pattern = "*-tongue-clos-cart.tsv",
    full.names = TRUE
)

tongues_clos <- read_aaa(
    aaa_files_clos,
    columns, 
    na.rm = TRUE
) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor) %>%
    group_by(speaker) %>%
    mutate(
        X.re = rescale(X),
        Y.re = rescale(Y)
    ) %>%
    ungroup() %>%
    mutate(
        vowel.ord = ordered(vowel, levels = c("a", "o", "u")),
        c2place.ord = ordered(c2place, levels = c("coronal", "velar")),
        c2phonation.ord = ordered(c2phonation, levels = c("voiceless", "voiced"))
    ) %>%
    arrange(rec.date, fan.line) %>%
    create_event_start("rec.date")

vowels <- list.files(path = "data/durations",
                   pattern = "*-vowel-durations.csv",
                   full.names = TRUE) %>%
    map_df(~read_csv(., na = "--undefined--")) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(
        index = as.factor(index),
        c2phonation = factor(c2phonation, levels = c("voiceless", "voiced"))
    ) %>%
    filter(!(file == "it04-002" | file == "pl03-020")) # filter obvious outliers
```

# Vowel duration

## Italian

```{r it-duration-lm}
it_vow_lm <- lmer(
    vowel.duration ~
        c2phonation +
        c2place +
        vowel +
        c2phonation:vowel +
        sentence.duration +
        (1+c2phonation|speaker) +
        (1|word),
    data = filter(vowels, language == "italian")
)

summary(it_vow_lm)

it_vow_lm_null <- lmer(
    vowel.duration ~
#        c2phonation +
        c2place +
        vowel +
        sentence.duration +
        (1+c2phonation|speaker) +
        (1|word),
    data = filter(vowels, language == "italian")
)

anova(it_vow_lm_null, it_vow_lm)
```

```{r it-duration-lm-plots}
plot(fitted(it_vow_lm),residuals(it_vow_lm))
qqnorm(resid(it_vow_lm))
plot(allEffects(it_vow_lm))
```

## Polish

```{r pl-duration-lm}
pl_vow_lm <- lmer(
    vowel.duration ~
        c2phonation +
        vowel +
        c2place +
        sentence.duration +
        (1+c2phonation|speaker) +
        (1|word),
    data = filter(vowels, language == "polish")
)

summary(pl_vow_lm)

pl_vow_lm_null <- lmer(
    vowel.duration ~
#        c2phonation +
        vowel +
        c2place +
        sentence.duration +
        (1+c2phonation|speaker) +
        (1|word),
    data = filter(vowels, language == "polish")
)

anova(pl_vow_lm_null, pl_vow_lm)
```

```{r pl-duration-lm-plots}
plot(fitted(pl_vow_lm),residuals(pl_vow_lm))
qqnorm(resid(pl_vow_lm))
plot(allEffects(pl_vow_lm))
```

# Tongue root advancement at maximum displacement

## Italian

### IT01

```{r it01-tra}
it01_max <- filter(tongues, speaker == "it01")

it01_gamm <- bam(
    Y ~
        X.re +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = it01_max,
    method = "fREML"
)

rho <- start_value_rho(it01_gamm)

it01_gamm_ar <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = it01_max,
    method = "ML",
    rho = rho,
    AR.start = it01_max$start.event
)

summary(it01_gamm_ar)

it01_gamm_ar_null <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = it01_max,
    method = "ML",
    rho = rho,
    AR.start = it01_max$start.event
)

compareML(it01_gamm_ar_null, it01_gamm_ar)
```

```{r it01-tra-plot}
plot_gamsd(
    it01_gamm_ar,
    view = "X",
    comparison = list(c2phonation.ord = c("voiceless", "voiced")),
    conditions = list(c2place.ord = "coronal")
)
```

### IT02

```{r it02-tra}
it02_max <- filter(tongues, speaker == "it02")

it02_gamm <- bam(
    Y ~
        X.re +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = it02_max,
    method = "fREML"
)

rho <- start_value_rho(it02_gamm)

it02_gamm_ar <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = it02_max,
    method = "ML",
    rho = rho,
    AR.start = it02_max$start.event
)

summary(it02_gamm_ar)

it02_gamm_ar_null <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = it02_max,
    method = "ML",
    rho = rho,
    AR.start = it02_max$start.event
)

compareML(it02_gamm_ar_null, it02_gamm_ar)
```

```{r it02-tra-plot}
plot_gamsd(
    it02_gamm_ar,
    view = "X",
    comparison = list(c2phonation.ord = c("voiceless", "voiced")),
    conditions = list(c2place.ord = "coronal")
)
```

## Polish

### PL02

```{r pl02-tra}
pl02_max <- filter(tongues, speaker == "pl02", X > -20)

pl02_gamm <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = pl02_max,
    method = "ML"
)

rho <- start_value_rho(pl02_gamm)

pl02_gamm_ar <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = pl02_max,
    method = "ML",
    rho = rho,
    AR.start = pl02_max$start.event
)

summary(pl02_gamm_ar)

pl02_gamm_ar_null <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = pl02_max,
    method = "ML"
)

compareML(pl02_gamm_ar_null, pl02_gamm_ar)
```

```{r pl02-tra}
plot_gamsd(
    pl02_gamm_ar,
    view = "X",
    comparison = list(c2phonation.ord = c("voiceless", "voiced")),
    conditions = list(c2place.ord = "coronal")
)
```

### PL04

```{r pl04-tra}
pl04_max <- filter(tongues, speaker == "pl04", X > -30)

pl04_gamm <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = pl04_max,
    method = "ML"
)

rho <- start_value_rho(pl04_gamm)

pl04_gamm_ar <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = pl04_max,
    method = "ML",
    rho = rho,
    AR.start = pl04_max$start.event
)

summary(pl04_gamm_ar)

pl04_gamm_ar_null <- bam(
    Y ~
        X +
        s(X, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = pl04_max,
    method = "ML"
)

compareML(pl04_gamm_ar_null, pl04_gamm_ar)
```

```{r pl04-tra}
plot_gamsd(
    pl04_gamm_ar,
    view = "X",
    comparison = list(c2phonation.ord = c("voiceless", "voiced")),
    conditions = list(c2place.ord = "coronal")
)
```
